services:
  - type: web
    runtime: node
    name: closedboard-api
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
